"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import * as _interactions from "./interactions";
import * as _utils from "./utils";
import _styles from "./RtIntegration.module.css";

const _interactionsData = JSON.parse(
  '{"events":{"e-12":{"id":"e-12","name":"","animationType":"preset","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-13","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-13"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6ee","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6ee","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":0,"scrollOffsetUnit":"%","delay":null,"direction":null,"effectIn":null},"createdOn":1753965912365,"origin":["693864c3fbe2f2227213641b","e-305"]},"e-15":{"id":"e-15","name":"","animationType":"preset","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"SLIDE_EFFECT","instant":false,"config":{"actionListId":"slideInBottom","autoStopEventId":"e-14"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f5","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f5","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":12,"scrollOffsetUnit":"%","delay":100,"direction":"BOTTOM","effectIn":true},"createdOn":1754306961366,"origin":["693864c3fbe2f2227213641b","e-307"]},"e-17":{"id":"e-17","name":"","animationType":"preset","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"SLIDE_EFFECT","instant":false,"config":{"actionListId":"slideInBottom","autoStopEventId":"e-16"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f7","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f7","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":12,"scrollOffsetUnit":"%","delay":200,"direction":"BOTTOM","effectIn":true},"createdOn":1754306970879,"origin":["693864c3fbe2f2227213641b","e-301"]},"e-19":{"id":"e-19","name":"","animationType":"custom","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-15","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-18"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f9","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"55e55bff-e804-1154-87c6-e98cd3d1c6f9","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":0,"scrollOffsetUnit":"%","delay":null,"direction":null,"effectIn":null},"createdOn":1753859074691,"origin":["693864c3fbe2f2227213641b","e-300"]},"e-21":{"id":"e-21","name":"","animationType":"preset","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"GROW_EFFECT","instant":false,"config":{"actionListId":"growIn","autoStopEventId":"e-22"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"55e55bff-e804-1154-87c6-e98cd3d1c712","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"55e55bff-e804-1154-87c6-e98cd3d1c712","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":12,"scrollOffsetUnit":"%","delay":300,"direction":null,"effectIn":true},"createdOn":1753859994329,"origin":["693864c3fbe2f2227213641b","e-299"]}},"actionLists":{"a-13":{"id":"a-13","origin":["693864c3fbe2f2227213641b","a-50"],"title":"Faq Top Animation 5","actionItemGroups":[{"actionItems":[{"id":"a-13-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"SIBLINGS","selector":".lokendra-singhs-stunning-site--rt-faq-image-overlay","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1c8"]},"xValue":0,"xUnit":"%","yUnit":"PX","zUnit":"PX"}}]},{"actionItems":[{"id":"a-13-n-2","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"ease","duration":1800,"target":{"useEventTarget":"SIBLINGS","selector":".lokendra-singhs-stunning-site--rt-faq-image-overlay","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1c8"]},"xValue":100,"xUnit":"%","yUnit":"PX","zUnit":"PX"}}]}],"useFirstGroupAsInitialState":false,"createdOn":1747040293995},"a-15":{"id":"a-15","origin":["693864c3fbe2f2227213641b","a-65"],"title":"Integration Icon Pop Up 2","actionItemGroups":[{"actionItems":[{"id":"a-15-n","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v1","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1cf"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-2","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v6","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1ca"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-3","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v5","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1d7"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-4","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v4","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1db"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-5","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v3","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1da"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-6","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v2","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1dc"]},"xValue":0,"yValue":0,"locked":true}}]},{"actionItems":[{"id":"a-15-n-7","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v1","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1cf"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-8","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v2","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1dc"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-9","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v3","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1da"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-10","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v4","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1db"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-11","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v5","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1d7"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-12","actionTypeId":"TRANSFORM_SCALE","config":{"delay":1000,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v6","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1ca"]},"xValue":1,"yValue":1,"locked":true}}]},{"actionItems":[{"id":"a-15-n-13","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v1","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1cf"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-14","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v6","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1ca"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-15","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v5","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1d7"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-16","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v4","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1db"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-17","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v3","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1da"]},"xValue":0,"yValue":0,"locked":true}},{"id":"a-15-n-18","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v2","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1dc"]},"xValue":1,"yValue":1,"locked":true}}]},{"actionItems":[{"id":"a-15-n-19","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v1","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1cf"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-20","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v2","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1dc"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-21","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v3","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1da"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-22","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v4","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1db"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-23","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v5","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1d7"]},"xValue":1,"yValue":1,"locked":true}},{"id":"a-15-n-24","actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"inOutCirc","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".lokendra-singhs-stunning-site--rt-integration-icon-v6","selectorGuids":["5b8c5c86-c18c-46f2-fad5-8cc951d2d1ca"]},"xValue":1,"yValue":1,"locked":true}}]}],"useFirstGroupAsInitialState":true,"createdOn":1753859076881},"slideInBottom":{"id":"slideInBottom","useFirstGroupAsInitialState":true,"actionItemGroups":[{"actionItems":[{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":0}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":0,"yValue":100,"xUnit":"PX","yUnit":"PX","zUnit":"PX"}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":0,"yValue":0,"xUnit":"PX","yUnit":"PX","zUnit":"PX"}},{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":1}}]}]},"growIn":{"id":"growIn","useFirstGroupAsInitialState":true,"actionItemGroups":[{"actionItems":[{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":0}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":0.7500000000000001,"yValue":0.7500000000000001}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_SCALE","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":1,"yValue":1}},{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":1}}]}]}},"site":{"mediaQueries":[{"key":"main","min":992,"max":10000},{"key":"medium","min":768,"max":991},{"key":"small","min":480,"max":767},{"key":"tiny","min":0,"max":479}]}}'
);

export function RtIntegration({ as: _Component = _Builtin.Section }) {
  _interactions.useInteractions(_interactionsData, _styles);

  return (
    <_Component
      className={_utils.cx(
        _styles,
        "lokendra-singhs-stunning-site--rt-integration",
        "lokendra-singhs-stunning-site--rt-position-relative"
      )}
      tag="section"
      grid={{
        type: "section",
      }}
    >
      <_Builtin.VFlex
        className={_utils.cx(
          _styles,
          "lokendra-singhs-stunning-site--rt-faq-top-image-main",
          "lokendra-singhs-stunning-site--rt-integration-top-image",
          "lokendra-singhs-stunning-site--rt-overflow-hidden",
          "lokendra-singhs-stunning-site--rt-tab-display-none"
        )}
        tag="div"
      >
        <_Builtin.HFlex
          className={_utils.cx(
            _styles,
            "lokendra-singhs-stunning-site--rt-faq-top-image-wrap"
          )}
          data-w-id="55e55bff-e804-1154-87c6-e98cd3d1c6ee"
          tag="div"
        >
          <_Builtin.Image
            width="1229"
            height="569"
            loading="lazy"
            alt="Optimatia-home-two-faq-glow"
            src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fbe_65f6b2d511146151661552f923f2b282_optimatia-home-two-faq-glow.svg"
          />
        </_Builtin.HFlex>
        <_Builtin.Block
          className={_utils.cx(
            _styles,
            "lokendra-singhs-stunning-site--rt-faq-image-overlay"
          )}
          tag="div"
        />
      </_Builtin.VFlex>
      <_Builtin.Block
        className={_utils.cx(
          _styles,
          "lokendra-singhs-stunning-site--rt-testimonial-v2-content-wrap",
          "lokendra-singhs-stunning-site--rt-overflow-hidden"
        )}
        tag="div"
      >
        <_Builtin.BlockContainer
          className={_utils.cx(
            _styles,
            "lokendra-singhs-stunning-site--rt-container-small"
          )}
          tag="div"
          grid={{
            type: "container",
          }}
        >
          <_Builtin.HFlex
            className={_utils.cx(
              _styles,
              "lokendra-singhs-stunning-site--rt-integration-heading-main"
            )}
            tag="div"
          >
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "lokendra-singhs-stunning-site--rt-integration-heading-wrap",
                "lokendra-singhs-stunning-site--rt-desktop-text-center"
              )}
              tag="div"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "lokendra-singhs-stunning-site--rt-sub-text",
                  "lokendra-singhs-stunning-site--rt-linear",
                  "lokendra-singhs-stunning-site--rt-sub-text-bottom-gap"
                )}
                data-w-id="55e55bff-e804-1154-87c6-e98cd3d1c6f5"
                tag="div"
              >
                {"[ integration ]"}
              </_Builtin.Block>
              <_Builtin.Heading
                data-w-id="55e55bff-e804-1154-87c6-e98cd3d1c6f7"
                tag="h2"
              >
                {"Seamless AI integration with your existing systems"}
              </_Builtin.Heading>
            </_Builtin.Block>
          </_Builtin.HFlex>
          <_Builtin.VFlex
            className={_utils.cx(
              _styles,
              "lokendra-singhs-stunning-site--rt-integration-image-main",
              "lokendra-singhs-stunning-site--rt-position-relative"
            )}
            data-w-id="55e55bff-e804-1154-87c6-e98cd3d1c6f9"
            tag="div"
          >
            <_Builtin.HFlex
              className={_utils.cx(
                _styles,
                "lokendra-singhs-stunning-site--rt-integration-image-wrap",
                "lokendra-singhs-stunning-site--rt-overflow-hidden",
                "lokendra-singhs-stunning-site--rt-landscape-display-none"
              )}
              tag="div"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "lokendra-singhs-stunning-site--rt-integration-image-v1",
                  "lokendra-singhs-stunning-site--rt-position-relative"
                )}
                tag="div"
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-auto-fit",
                    "lokendra-singhs-stunning-site--rt-desktop-image-full-width"
                  )}
                  width="574"
                  height="308"
                  loading="lazy"
                  alt="Optimatia-home-three-integration-line"
                  src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fbd_acce81db8362d20ccc711acf6e3e8497_optimatia-home-three-integration-line.svg"
                />
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-overlay",
                    "lokendra-singhs-stunning-site--rt-one"
                  )}
                  tag="div"
                />
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-icon-main"
                  )}
                  tag="div"
                >
                  <_Builtin.HFlex
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon-v1",
                      "lokendra-singhs-stunning-site--rt-landscape-display-none"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "lokendra-singhs-stunning-site--rt-integration-icon"
                      )}
                      width="54"
                      height="54"
                      loading="lazy"
                      alt="Optimatia-home-three-integration-icon"
                      src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fbc_aa9df05261710cea88981bbe962eb2f4_optimatia-home-three-integration-icon.svg"
                    />
                  </_Builtin.HFlex>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon-v2"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "lokendra-singhs-stunning-site--rt-integration-icon"
                      )}
                      width="54"
                      height="54"
                      loading="lazy"
                      alt="Optimatia-home-three-integration-icon"
                      src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fbb_4d83f9da839244bd3996d686ba5b7ed6_optimatia-home-three-integration-icon.svg"
                    />
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon-v3"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "lokendra-singhs-stunning-site--rt-integration-icon"
                      )}
                      width="auto"
                      height="auto"
                      loading="lazy"
                      alt="Optimatia-home-three-integration-icon"
                      src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb8_79c371b689b7e24c3c31c9be76a41c60_optimatia-home-three-integration-icon.svg"
                    />
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
              <_Builtin.VFlex
                className={_utils.cx(
                  _styles,
                  "lokendra-singhs-stunning-site--rt-integration-icon-wrap"
                )}
                tag="div"
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-auto-fit",
                    "lokendra-singhs-stunning-site--rt-tab-image-full-width"
                  )}
                  width="106"
                  height="102"
                  loading="lazy"
                  alt="Optimatia-about-integration-icon"
                  src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fba_d0c2a71aec7c3f18e7b263ac0c72f152_optimatia-about-integration-icon.svg"
                />
              </_Builtin.VFlex>
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "lokendra-singhs-stunning-site--rt-integration-image-v2",
                  "lokendra-singhs-stunning-site--rt-position-relative"
                )}
                tag="div"
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-auto-fit",
                    "lokendra-singhs-stunning-site--rt-desktop-image-full-width"
                  )}
                  width="575"
                  height="309"
                  loading="lazy"
                  alt="Optimatia-home-three-integration-line"
                  src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb9_2f04aa737471be4324433f61d8618900_optimatia-home-three-integration-line.svg"
                />
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-overlay",
                    "lokendra-singhs-stunning-site--rt-two"
                  )}
                  tag="div"
                />
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-icon-v4"
                  )}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon"
                    )}
                    width="54"
                    height="54"
                    loading="lazy"
                    alt="Optimatia-home-three-integration-icon"
                    src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb8_79c371b689b7e24c3c31c9be76a41c60_optimatia-home-three-integration-icon.svg"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-icon-v5",
                    "lokendra-singhs-stunning-site--rt-landscape-display-none"
                  )}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon"
                    )}
                    width="53"
                    height="53"
                    loading="lazy"
                    alt="Optimatia-home-three-integration-icon"
                    src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb7_8aad1e9cb326f3050e494db0965651cb_optimatia-home-three-integration-icon.svg"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "lokendra-singhs-stunning-site--rt-integration-icon-v6"
                  )}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(
                      _styles,
                      "lokendra-singhs-stunning-site--rt-integration-icon"
                    )}
                    width="53"
                    height="53"
                    loading="lazy"
                    alt="Optimatia-home-three-integration-icon"
                    src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb6_408e8cd8498b4f1384c87c5e7303ec31_optimatia-home-three-integration-icon.svg"
                  />
                </_Builtin.Block>
              </_Builtin.Block>
            </_Builtin.HFlex>
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "lokendra-singhs-stunning-site--rt-integration-image"
              )}
              tag="div"
            >
              <_Builtin.Image
                className={_utils.cx(
                  _styles,
                  "lokendra-singhs-stunning-site--rt-auto-fit",
                  "lokendra-singhs-stunning-site--rt-desktop-image-full-width"
                )}
                width="1305"
                height="401"
                loading="lazy"
                alt="Optimatia-home-three-integration"
                src="https://cdn.prod.website-files.com/6937648cfb0c89dbe6623f0f/693863e7e9c49045040b1fb2_e6a489fb413f07257e2ea0c9cc8250fe_optimatia-home-three-integration.webp"
              />
            </_Builtin.Block>
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "lokendra-singhs-stunning-site--rt-integration-gradient",
                "lokendra-singhs-stunning-site--rt-mobile-display-none"
              )}
              data-w-id="55e55bff-e804-1154-87c6-e98cd3d1c712"
              tag="div"
            />
          </_Builtin.VFlex>
        </_Builtin.BlockContainer>
      </_Builtin.Block>
    </_Component>
  );
}
